In [1]:
pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (6.33.5)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Installing collected packages: kagglesdk, kagglehub

   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   ---------------------------------------- 0/2 [kagglesdk]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   -------------------- ------------------- 1/2 [kagglehub]
   ---------------------------------------- 2/2 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import kagglehub 

path = kagglehub.dataset_download("shivamb/netflix-shows")

print(path)

C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to C:\Users\DELL\.cache\kagglehub\datasets\shivamb\netflix-shows\5.archive...

100%|██████████| 1.34M/1.34M [00:00<00:00, 2.63MB/s]

Extracting files...
C:\Users\DELL\.cache\kagglehub\datasets\shivamb\netflix-shows\versions\5

In [3]:
import os 
print(os.listdir(path))

['netflix_titles.csv']

In [4]:
import pandas as pd

In [5]:
file_path = os.path.join(path, "netflix_titles.csv")

df = pd.read_csv(file_path)

In [6]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [7]:
df.shape

(8807, 12)

In [8]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [10]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [11]:
(df.isnull().sum()/len(df)*100).round(2)

show_id          0.00
type             0.00
title            0.00
director        29.91
cast             9.37
country          9.44
date_added       0.11
release_year     0.00
rating           0.05
duration         0.03
listed_in        0.00
description      0.00
dtype: float64

In [12]:
df.groupby("type")["director"].apply(lambda x: x.isnull().sum())

type
Movie       188
TV Show    2446
Name: director, dtype: int64

In [13]:
df.groupby("type")["director"].apply(
    lambda x: round(x.isnull().mean() * 100, 2)
)

type
Movie       3.07
TV Show    91.41
Name: director, dtype: float64

In [14]:
df.groupby("type")["cast"].apply(
    lambda x: round(x.isnull().mean() * 100 , 2)
)

type
Movie       7.75
TV Show    13.08
Name: cast, dtype: float64

In [15]:
df.groupby("type")["country"].apply(
    lambda x: round(x.isnull().mean() * 100 , 2)
)

type
Movie       7.18
TV Show    14.61
Name: country, dtype: float64

In [16]:
df[df["date_added"].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6066,s6067,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6174,s6175,TV Show,Anthony Bourdain: Parts Unknown,NaN,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
6795,s6796,TV Show,Frasier,NaN,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
6806,s6807,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
6901,s6902,TV Show,Gunslinger Girl,NaN,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
7196,s7197,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
7254,s7255,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
7406,s7407,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
7847,s7848,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
8182,s8183,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [17]:
df[df["rating"].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [18]:
df[df["duration"].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [21]:
df["type"].value_counts(normalize=True).mul(100).round(2)

type
Movie      69.62
TV Show    30.38
Name: proportion, dtype: float64

In [22]:
df["rating"].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [24]:
df[df["rating"].str.contains("min", na=False)][["title","type","rating","duration"]]

                                     title   type  rating duration
5541                       Louis C.K. 2017  Movie  74 min      NaN
5794                 Louis C.K.: Hilarious  Movie  84 min      NaN
5813  Louis C.K.: Live at the Comedy Store  Movie  66 min      NaN

In [25]:
df["duration"].value_counts().head(20)

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
88 min        116
101 min       116
103 min       114
106 min       111
100 min       108
89 min        106
Name: count, dtype: int64

In [26]:
mask = df["rating"].str.contains("min" , na=False)

df.loc[mask, "duration"] = df.loc[mask, "rating"]
df.loc[mask, "rating"] = pd.NA

In [27]:
df[df["title"].isin([
    "Louis C.K. 2017",
    "Louis C.K.: Hilarious",
    "Louis C.K.: Live at the Comedy Store"
])][["title", "rating", "duration"]]

                                     title rating duration
5541                       Louis C.K. 2017    NaN   74 min
5794                 Louis C.K.: Hilarious    NaN   84 min
5813  Louis C.K.: Live at the Comedy Store    NaN   66 min

In [28]:
pd.crosstab(df["type"],df["rating"])

rating,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
type,,,,,,,,,,,,,,
Movie,41,3,75,287,490,797,1427,126,2062,540,131,139,5,3
TV Show,0,0,5,0,0,2,733,94,1145,323,176,195,1,0

In [29]:
df["rating"].value_counts()

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [30]:
df["country"].value_counts().head(20)

country
United States                    2818
India                             972
United Kingdom                    419
Japan                             245
South Korea                       199
Canada                            181
Spain                             145
France                            124
Mexico                            110
Egypt                             106
Turkey                            105
Nigeria                            95
Australia                          87
Taiwan                             81
Indonesia                          79
Brazil                             77
United Kingdom, United States      75
Philippines                        75
United States, Canada              73
Germany                            67
Name: count, dtype: int64

In [31]:
df.groupby("type")["country"].apply(
    lambda x: round(x.isnull().mean() * 100 , 2)
)

type
Movie       7.18
TV Show    14.61
Name: country, dtype: float64

In [32]:
(df.select_dtypes(include="object")=="").sum()

C:\Users\DELL\AppData\Local\Temp\ipykernel_26096\2535060054.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  (df.select_dtypes(include="object")=="").sum()

show_id        0
type           0
title          0
director       0
cast           0
country        0
date_added     0
rating         0
duration       0
listed_in      0
description    0
dtype: int64

In [33]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [34]:
df.dtypes

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [36]:
df["date_added"] = pd.to_datetime(df["date_added"], format="mixed")

In [37]:
df[["date_added"]].dtypes

date_added    datetime64[us]
dtype: object

In [38]:
df["date_added"].isnull().sum()

np.int64(10)

In [39]:
df["duration"].str.extract(r"([A-Za-z]+)$")[0].value_counts()

0
min        6131
Season     1793
Seasons     883
Name: count, dtype: int64

In [40]:
df["duration"].str.extract(r"(\d+)")[0].head(10)

0     90
1      2
2      1
3      1
4      2
5      1
6     91
7    125
8      9
9    104
Name: 0, dtype: str

In [41]:
df["duration_value"] = pd.to_numeric(
    df["duration"].str.extract(r"(\d+)")[0]
)

In [42]:
df[["duration", "duration_value"]].head(10)

    duration  duration_value
0     90 min              90
1  2 Seasons               2
2   1 Season               1
3   1 Season               1
4  2 Seasons               2
5   1 Season               1
6     91 min              91
7    125 min             125
8  9 Seasons               9
9    104 min             104

In [43]:
df["duration_unit"] = df["duration"].str.extract(r"([A-Za-z]+)$")[0]

In [44]:
df[["duration", "duration_value", "duration_unit"]].head(10)

    duration  duration_value duration_unit
0     90 min              90           min
1  2 Seasons               2       Seasons
2   1 Season               1        Season
3   1 Season               1        Season
4  2 Seasons               2       Seasons
5   1 Season               1        Season
6     91 min              91           min
7    125 min             125           min
8  9 Seasons               9       Seasons
9    104 min             104           min

In [45]:
df["duration_unit"] = df["duration_unit"].replace({
    "Season": "season",
    "Seasons": "season",
    "min": "min"
})

In [46]:
df["duration_unit"].value_counts()

duration_unit
min       6131
season    2676
Name: count, dtype: int64

In [47]:
df[["duration", "duration_value", "duration_unit"]].isnull().sum()

duration          0
duration_value    0
duration_unit     0
dtype: int64

In [48]:
df[df["director"].isnull()][
    ["type", "title" , "country" , "release_year","director"]
].head(10)

,type,title,country,release_year,director
1,TV Show,Blood & Water,South Africa,2021,NaN
3,TV Show,Jailbirds New Orleans,NaN,2021,NaN
4,TV Show,Kota Factory,India,2021,NaN
10,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,2021,NaN
14,TV Show,Crime Stories: India Detectives,NaN,2021,NaN
15,TV Show,Dear White People,United States,2021,NaN
17,TV Show,Falsa identidad,Mexico,2020,NaN
19,TV Show,Jaguar,NaN,2021,NaN
21,TV Show,Resurrection: Ertugrul,Turkey,2018,NaN
25,TV Show,Love on the Spectrum,Australia,2021,NaN

In [49]:
df["director"].nunique()

4528

In [50]:
df["director"].dropna().head(10)

0                   Kirsten Johnson
2                   Julien Leclercq
5                     Mike Flanagan
6     Robert Cullen, José Luis Ucha
7                      Haile Gerima
8                   Andy Devonshire
9                    Theodore Melfi
11                Kongkiat Komesiri
12              Christian Schwochow
13                    Bruno Garotti
Name: director, dtype: str

In [51]:
df["director"] = df["director"].fillna("Unknown")

In [52]:
df["director"].isnull().sum()

np.int64(0)

In [53]:
df[df["cast"].isnull()][
    ["type" , "title" , "director" , "country" , "cast"]
].head(10)

,type,title,director,country,cast
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,NaN
3,TV Show,Jailbirds New Orleans,Unknown,NaN,NaN
10,TV Show,"Vendetta: Truth, Lies and The Mafia",Unknown,NaN,NaN
14,TV Show,Crime Stories: India Detectives,Unknown,NaN,NaN
16,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN
20,TV Show,Monsters Inside: The 24 Faces of Billy Milligan,Olivier Megaton,NaN,NaN
45,Movie,My Heroes Were Cowboys,Tyler Greco,NaN,NaN
66,TV Show,Raja Rasoi Aur Anya Kahaniyan,Unknown,India,NaN
69,TV Show,Stories by Rabindranath Tagore,Unknown,India,NaN
74,TV Show,The World's Most Amazing Vacation Rentals,Unknown,NaN,NaN

In [54]:
df["cast"] = df["cast"].fillna("Unknown")

In [55]:
df["cast"].isnull().sum()

np.int64(0)

In [56]:
df[df["country"].isnull()][
    ["type", "title" , "director" , "cast" , "country"]
].head(10)

,type,title,director,cast,country
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN
3,TV Show,Jailbirds New Orleans,Unknown,Unknown,NaN
5,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN
6,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN
10,TV Show,"Vendetta: Truth, Lies and The Mafia",Unknown,Unknown,NaN
11,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN
13,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN
14,TV Show,Crime Stories: India Detectives,Unknown,Unknown,NaN
16,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",Unknown,NaN
18,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN

In [57]:
df["country"] = df["country"].fillna("Unknown")

In [58]:
df["country"].isnull().sum()

np.int64(0)

In [59]:
df.isnull().sum()

show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
duration_value     0
duration_unit      0
dtype: int64

In [60]:
df.dtypes

show_id                      str
type                         str
title                        str
director                     str
cast                         str
country                      str
date_added        datetime64[us]
release_year               int64
rating                       str
duration                     str
listed_in                    str
description                  str
duration_value             int64
duration_unit                str
dtype: object

In [61]:
df["type"].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [62]:
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
NaN            7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [63]:
df["release_year"].describe()

count    8807.000000
mean     2014.180198
std         8.819312
min      1925.000000
25%      2013.000000
50%      2017.000000
75%      2019.000000
max      2021.000000
Name: release_year, dtype: float64

In [65]:
df["release_year"].value_counts().sort_index().head(20)

release_year
1925    1
1942    2
1943    3
1944    3
1945    4
1946    2
1947    1
1954    2
1955    3
1956    2
1958    3
1959    1
1960    4
1961    1
1962    3
1963    2
1964    2
1965    2
1966    1
1967    5
Name: count, dtype: int64

In [66]:
df[["country", "listed_in"]].head(10)

,country,listed_in
0,United States,Documentaries
1,South Africa,"International TV Shows, TV Dramas, TV Mysteries"
2,Unknown,"Crime TV Shows, International TV Shows, TV Act..."
3,Unknown,"Docuseries, Reality TV"
4,India,"International TV Shows, Romantic TV Shows, TV ..."
5,Unknown,"TV Dramas, TV Horror, TV Mysteries"
6,Unknown,Children & Family Movies
7,"United States, Ghana, Burkina Faso, United Kin...","Dramas, Independent Movies, International Movies"
8,United Kingdom,"British TV Shows, Reality TV"
9,United States,"Comedies, Dramas"

In [67]:
print("Pays multiples :", df["country"].str.contains(",", na=False).sum())
print("Catégories multiples :", df["listed_in"].str.contains(",", na=False).sum())

Pays multiples : 1320
Catégories multiples : 6787

In [68]:
df["show_id"].nunique()

8807

In [69]:
len(df)

8807

In [70]:
print("Réalisateurs multiples :", df["director"].str.contains(",", na=False).sum())
print("Acteurs multiples :", df["cast"].str.contains(",", na=False).sum())

Réalisateurs multiples : 614
Acteurs multiples : 7101

In [71]:
test = pd.DataFrame({
    "show_id": ["s1", "s2", "s3"],
    "country": [
        "United States",
        "United States, Canada",
        "India, Japan, South Korea"
    ]
})

test

  show_id                    country
0      s1              United States
1      s2      United States, Canada
2      s3  India, Japan, South Korea

In [72]:
test["country"].str.split(", ")

0                [United States]
1        [United States, Canada]
2    [India, Japan, South Korea]
Name: country, dtype: object

In [73]:
test["country"].str.split(", ").explode()

0    United States
1    United States
1           Canada
2            India
2            Japan
2      South Korea
Name: country, dtype: str

In [74]:
test_country = test.copy()

In [75]:
test_country["country"] = test_country["country"].str.split(", ")

In [76]:
test_country = test_country.explode("country")

In [77]:
test_country

  show_id        country
0      s1  United States
1      s2  United States
1      s2         Canada
2      s3          India
2      s3          Japan
2      s3    South Korea

In [78]:
test_country = test_country.reset_index(drop=True)

In [79]:
test_country

  show_id        country
0      s1  United States
1      s2  United States
2      s2         Canada
3      s3          India
4      s3          Japan
5      s3    South Korea

In [80]:
content_country = df[["show_id","country"]].copy()

In [81]:
content_country.head()

  show_id        country
0      s1  United States
1      s2   South Africa
2      s3        Unknown
3      s4        Unknown
4      s5          India

In [82]:
content_country["country"] = content_country["country"].str.split(", ")

In [83]:
content_country.head(10)

  show_id                                            country
0      s1                                    [United States]
1      s2                                     [South Africa]
2      s3                                          [Unknown]
3      s4                                          [Unknown]
4      s5                                            [India]
5      s6                                          [Unknown]
6      s7                                          [Unknown]
7      s8  [United States, Ghana, Burkina Faso, United Ki...
8      s9                                   [United Kingdom]
9     s10                                    [United States]

In [84]:
content_country = content_country.explode("country")

In [85]:
content_country.head(15)

  show_id         country
0      s1   United States
1      s2    South Africa
2      s3         Unknown
3      s4         Unknown
4      s5           India
5      s6         Unknown
6      s7         Unknown
7      s8   United States
7      s8           Ghana
7      s8    Burkina Faso
7      s8  United Kingdom
7      s8         Germany
7      s8        Ethiopia
8      s9  United Kingdom
9     s10   United States

In [86]:
content_country = content_country.reset_index(drop=True)

In [87]:
content_country.head(15)

   show_id         country
0       s1   United States
1       s2    South Africa
2       s3         Unknown
3       s4         Unknown
4       s5           India
5       s6         Unknown
6       s7         Unknown
7       s8   United States
8       s8           Ghana
9       s8    Burkina Faso
10      s8  United Kingdom
11      s8         Germany
12      s8        Ethiopia
13      s9  United Kingdom
14     s10   United States

In [88]:
print("Nombre de contenus uniques :", content_country["show_id"].nunique())
print("Nombre de lignes dans content_country :", len(content_country))
print("Nombre de contenus dans df :", len(df))

Nombre de contenus uniques : 8807
Nombre de lignes dans content_country : 10845
Nombre de contenus dans df : 8807

In [89]:
content_category = df[["show_id", "listed_in"]].copy()

In [90]:
content_category.head()

  show_id                                          listed_in
0      s1                                      Documentaries
1      s2    International TV Shows, TV Dramas, TV Mysteries
2      s3  Crime TV Shows, International TV Shows, TV Act...
3      s4                             Docuseries, Reality TV
4      s5  International TV Shows, Romantic TV Shows, TV ...

In [91]:
content_category["listed_in"] = content_category["listed_in"].str.split(", ")

In [92]:
content_category.head()

  show_id                                          listed_in
0      s1                                    [Documentaries]
1      s2  [International TV Shows, TV Dramas, TV Mysteries]
2      s3  [Crime TV Shows, International TV Shows, TV Ac...
3      s4                           [Docuseries, Reality TV]
4      s5  [International TV Shows, Romantic TV Shows, TV...

In [93]:
content_category = content_category.explode("listed_in")

In [94]:
content_category = content_category.reset_index(drop=True)

In [95]:
content_category.head(15)

   show_id               listed_in
0       s1           Documentaries
1       s2  International TV Shows
2       s2               TV Dramas
3       s2            TV Mysteries
4       s3          Crime TV Shows
5       s3  International TV Shows
6       s3   TV Action & Adventure
7       s4              Docuseries
8       s4              Reality TV
9       s5  International TV Shows
10      s5       Romantic TV Shows
11      s5             TV Comedies
12      s6               TV Dramas
13      s6               TV Horror
14      s6            TV Mysteries

In [96]:
print("Nombre de contenus uniques :", content_category["show_id"].nunique())
print("Nombre de lignes dans content_category :", len(content_category))
print("Nombre de contenus dans df :", len(df))

Nombre de contenus uniques : 8807
Nombre de lignes dans content_category : 19323
Nombre de contenus dans df : 8807

In [97]:
countries = content_country[["country"]].drop_duplicates()

In [98]:
countries.head(20)

            country
0     United States
1      South Africa
2           Unknown
4             India
8             Ghana
9      Burkina Faso
10   United Kingdom
11          Germany
12         Ethiopia
18   Czech Republic
23           Mexico
27           Turkey
31        Australia
37           France
45          Finland
46            China
47           Canada
58            Japan
61          Nigeria
102           Spain

In [99]:
countries = countries.reset_index(drop=True)

In [100]:
countries.head(20)

           country
0    United States
1     South Africa
2          Unknown
3            India
4            Ghana
5     Burkina Faso
6   United Kingdom
7          Germany
8         Ethiopia
9   Czech Republic
10          Mexico
11          Turkey
12       Australia
13          France
14         Finland
15           China
16          Canada
17           Japan
18         Nigeria
19           Spain

In [101]:
countries["country_id"] = countries.index + 1

In [102]:
countries.head(20)

           country  country_id
0    United States           1
1     South Africa           2
2          Unknown           3
3            India           4
4            Ghana           5
5     Burkina Faso           6
6   United Kingdom           7
7          Germany           8
8         Ethiopia           9
9   Czech Republic          10
10          Mexico          11
11          Turkey          12
12       Australia          13
13          France          14
14         Finland          15
15           China          16
16          Canada          17
17           Japan          18
18         Nigeria          19
19           Spain          20

In [103]:
content_country = content_country.merge(
    countries,
    on="country",
    how="left"
)

In [104]:
content_country.head(15)

   show_id         country  country_id
0       s1   United States           1
1       s2    South Africa           2
2       s3         Unknown           3
3       s4         Unknown           3
4       s5           India           4
5       s6         Unknown           3
6       s7         Unknown           3
7       s8   United States           1
8       s8           Ghana           5
9       s8    Burkina Faso           6
10      s8  United Kingdom           7
11      s8         Germany           8
12      s8        Ethiopia           9
13      s9  United Kingdom           7
14     s10   United States           1

In [105]:
content_country = content_country[["show_id", "country_id"]]

In [106]:
content_country.head(15)

   show_id  country_id
0       s1           1
1       s2           2
2       s3           3
3       s4           3
4       s5           4
5       s6           3
6       s7           3
7       s8           1
8       s8           5
9       s8           6
10      s8           7
11      s8           8
12      s8           9
13      s9           7
14     s10           1

In [107]:
print("Nombre de lignes :", len(content_country))
print("Nombre de contenus uniques :", content_country["show_id"].nunique())
print("Nombre de country_id manquants :", content_country["country_id"].isna().sum())

Nombre de lignes : 10845
Nombre de contenus uniques : 8807
Nombre de country_id manquants : 0

In [108]:
categories = content_category[["listed_in"]].drop_duplicates()

In [109]:
categories = categories.reset_index(drop=True)

In [110]:
categories.head(20)

                    listed_in
0               Documentaries
1      International TV Shows
2                   TV Dramas
3                TV Mysteries
4              Crime TV Shows
5       TV Action & Adventure
6                  Docuseries
7                  Reality TV
8           Romantic TV Shows
9                 TV Comedies
10                  TV Horror
11   Children & Family Movies
12                     Dramas
13         Independent Movies
14       International Movies
15           British TV Shows
16                   Comedies
17  Spanish-Language TV Shows
18                  Thrillers
19            Romantic Movies

In [111]:
categories["category_id"] = categories.index + 1

In [112]:
categories.head(20)

                    listed_in  category_id
0               Documentaries            1
1      International TV Shows            2
2                   TV Dramas            3
3                TV Mysteries            4
4              Crime TV Shows            5
5       TV Action & Adventure            6
6                  Docuseries            7
7                  Reality TV            8
8           Romantic TV Shows            9
9                 TV Comedies           10
10                  TV Horror           11
11   Children & Family Movies           12
12                     Dramas           13
13         Independent Movies           14
14       International Movies           15
15           British TV Shows           16
16                   Comedies           17
17  Spanish-Language TV Shows           18
18                  Thrillers           19
19            Romantic Movies           20

In [113]:
content_category = content_category.merge(
    categories,
    on="listed_in",
    how="left"
)

In [114]:
content_category.head(15)

   show_id               listed_in  category_id
0       s1           Documentaries            1
1       s2  International TV Shows            2
2       s2               TV Dramas            3
3       s2            TV Mysteries            4
4       s3          Crime TV Shows            5
5       s3  International TV Shows            2
6       s3   TV Action & Adventure            6
7       s4              Docuseries            7
8       s4              Reality TV            8
9       s5  International TV Shows            2
10      s5       Romantic TV Shows            9
11      s5             TV Comedies           10
12      s6               TV Dramas            3
13      s6               TV Horror           11
14      s6            TV Mysteries            4

In [115]:
content_category = content_category[["show_id", "category_id"]]

In [116]:
content_category.head(15)

   show_id  category_id
0       s1            1
1       s2            2
2       s2            3
3       s2            4
4       s3            5
5       s3            2
6       s3            6
7       s4            7
8       s4            8
9       s5            2
10      s5            9
11      s5           10
12      s6            3
13      s6           11
14      s6            4

In [117]:
print("Nombre de lignes :", len(content_category))
print("Nombre de contenus uniques :", content_category["show_id"].nunique())
print("Nombre de category_id manquants :", content_category["category_id"].isna().sum())

Nombre de lignes : 19323
Nombre de contenus uniques : 8807
Nombre de category_id manquants : 0

In [118]:
content = df[
    [
        "show_id",
        "title",
        "type",
        "date_added",
        "release_year",
        "rating",
        "duration_value",
        "duration_unit",
        "director",
        "cast",
        "description"
    ]
].copy()

In [119]:
content.head()

,show_id,title,type,date_added,release_year,rating,duration_value,duration_unit,director,cast,description
0,s1,Dick Johnson Is Dead,Movie,2021-09-25,2020,PG-13,90,min,Kirsten Johnson,Unknown,"As her father nears the end of his life, filmm..."
1,s2,Blood & Water,TV Show,2021-09-24,2021,TV-MA,2,season,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...","After crossing paths at a party, a Cape Town t..."
2,s3,Ganglands,TV Show,2021-09-24,2021,TV-MA,1,season,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",To protect his family from a powerful drug lor...
3,s4,Jailbirds New Orleans,TV Show,2021-09-24,2021,TV-MA,1,season,Unknown,Unknown,"Feuds, flirtations and toilet talk go down amo..."
4,s5,Kota Factory,TV Show,2021-09-24,2021,TV-MA,2,season,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",In a city of coaching centers known to train I...

In [120]:
print("Nombre de lignes :", len(content))
print("Nombre de show_id uniques :", content["show_id"].nunique())
print("Nombre de show_id manquants :", content["show_id"].isna().sum())

Nombre de lignes : 8807
Nombre de show_id uniques : 8807
Nombre de show_id manquants : 0

In [121]:
print("Nombre de pays :", len(countries))
print("Nombre de catégories :", len(categories))

Nombre de pays : 128
Nombre de catégories : 42

In [122]:
print("=== CONTENT ===")
print("Lignes :", len(content))
print("show_id uniques :", content["show_id"].nunique())
print("show_id manquants :", content["show_id"].isna().sum())

print("\n=== COUNTRIES ===")
print("Lignes :", len(countries))
print("country_id uniques :", countries["country_id"].nunique())
print("country_id manquants :", countries["country_id"].isna().sum())

print("\n=== CATEGORIES ===")
print("Lignes :", len(categories))
print("category_id uniques :", categories["category_id"].nunique())
print("category_id manquants :", categories["category_id"].isna().sum())

print("\n=== CONTENT_COUNTRY ===")
print("Lignes :", len(content_country))
print("show_id uniques :", content_country["show_id"].nunique())
print("country_id manquants :", content_country["country_id"].isna().sum())

print("\n=== CONTENT_CATEGORY ===")
print("Lignes :", len(content_category))
print("show_id uniques :", content_category["show_id"].nunique())
print("category_id manquants :", content_category["category_id"].isna().sum())

=== CONTENT ===
Lignes : 8807
show_id uniques : 8807
show_id manquants : 0

=== COUNTRIES ===
Lignes : 128
country_id uniques : 128
country_id manquants : 0

=== CATEGORIES ===
Lignes : 42
category_id uniques : 42
category_id manquants : 0

=== CONTENT_COUNTRY ===
Lignes : 10845
show_id uniques : 8807
country_id manquants : 0

=== CONTENT_CATEGORY ===
Lignes : 19323
show_id uniques : 8807
category_id manquants : 0

In [123]:
pip install sqlalchemy pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (2.0.47)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: greenlet>=1 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\DELL\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [129]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [ ]:
password = "YourPassword"

encoded_password = quote_plus(password)

engine = create_engine(
    f"mysql+pymysql://root:{encoded_password}@localhost:3306/netflix_bi"
)

In [131]:
with engine.connect() as connection:
    print("Connexion MySQL réussie !")

Connexion MySQL réussie !

In [132]:
countries.to_sql(
    "countries",
    con=engine,
    if_exists="append",
    index=False
)

128

In [133]:
categories.to_sql(
    "categories",
    con=engine,
    if_exists="append",
    index=False
)

42

In [134]:
content.to_sql(
    "content",
    con=engine,
    if_exists="append",
    index=False
)

8807

In [135]:
content_country.to_sql(
    "content_country",
    con=engine,
    if_exists="append",
    index=False
)

10845

In [136]:
content_category.to_sql(
    "content_category",
    con=engine,
    if_exists="append",
    index=False
)

19323